# Numpy for Data Science

In [39]:
import numpy as np
np.__version__

'1.16.4'

1D arrays in numpy

In [52]:
##Normal 1D arrays, np.array
list1 = [1,2,3,4,5]
np.array(list1)
#or
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [61]:
#upcasting
np.array([1,2,3,4,5.0])

array([1., 2., 3., 4., 5.])

In [58]:
#dtypes in np.array
def dtype_array(dtype=None):
    print(np.array([1,2,3,4,5], dtype = dtype))
dtype_array()# default datatype to int
dtype_array(dtype=str)# dtype str
dtype_array(dtype=float)# dtype str
dtype_array(dtype=complex)#complex dtype

[1 2 3 4 5]
['1' '2' '3' '4' '5']
[1. 2. 3. 4. 5.]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


<p>arange - > Return an array object satisfying the specified requirements</p>
<p>ones -> Return a new array setting values to one</p>
<p>zeros - >Return a new array setting values to zero</p>
<p>empty -> Return a new uninitialized array</p>
<p>full -> Return a new array of given shape filled with value</p>
<p>ones_like -> Return an array of ones with shape and type of input</p>
<p>zeros_like -> Return an array of zeros with shape and type of input</p>
<p>empty_like -> Return an empty array with shape and type of input</p>
<p>full_like -> Return a new array with shape of input filled with value</p>

In [38]:
##numpy arange
print("array of 3 elements -> ", np.arange(3))
print("array of 3 float elements ->", np.arange(3.0))
print("array of number between 3 and 7(exclude) ->", np.arange(3,7))
print("array of number between 3 and 7(exclude) seperated by 2 ->", np.arange(3,7,2))

array of 3 elements ->  [0 1 2]
array of 3 float elements -> [0. 1. 2.]
array of number between 3 and 7(exclude) -> [3 4 5 6]
array of number between 3 and 7(exclude) seperated by 2 -> [3 5]


In [63]:
#create your own 1D array
def make_array(start_value=0, end_value=10, seperate_by=2):# start and end values default to 0 and 10(excluded)
    print(np.arange(start_value, end_value, seperate_by))
    
make_array(4,80,5)
make_array(12,18,1.5)

[ 4  9 14 19 24 29 34 39 44 49 54 59 64 69 74 79]
[12.  13.5 15.  16.5]


In [99]:
#np.ones
print('1D array of ones\n', np.ones(5))
print('1D array of ones. dtype int\n',np.ones((5,), dtype=int))

print('nd array of ones\n', np.ones((5,4)))
print('nd array of ones. dtype int\n',np.ones((5,4), dtype=int))

1D array of ones
 [1. 1. 1. 1. 1.]
1D array of ones. dtype int
 [1 1 1 1 1]
nd array of ones
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
nd array of ones. dtype int
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [96]:
#np.zeros
print('1D array of zeros\n', np.zeros(6))
print('1D array of zeros. dtype int\n',np.zeros((6,), dtype=int))

print('nd array of zeros\n', np.zeros((2,3)))
print('nd array of zeros. dtype int \n',np.zeros((6,4), dtype=int))

1D array of zeros
 [0. 0. 0. 0. 0. 0.]
1D array of zeros. dtype int
 [0 0 0 0 0 0]
nd array of zeros
 [[0. 0. 0.]
 [0. 0. 0.]]
nd array of zeros. dtype int 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [98]:
#np.empty
#Return a new array of given shape and type, without initializing entries.
print('1d empty array\n', np.empty(2)) # one dimesional
print('nd empty array\n ',np.empty([2, 2], dtype=int)) # multi dimesional

1d empty array
 [1.5e-323 2.5e-323]
nd empty array
  [[10 10]
 [10 10]]


In [100]:
# np.full
#Return a new array of given shape and type, filled with fill_value.
print('one dimesional full array \n ', np.full(5,np.inf)) # array filled with np.inf
print('multi -dimensional full array \n', np.full((2, 2), 10)) #array filled with 10

one dimesional full array 
  [inf inf inf inf inf]
multi -dimensional full array 
 [[10 10]
 [10 10]]
