# Numpy for Data Science

<p>NumPy arrays are a bit like Python lists, but still very much different at the same time</p>
<p> a NumPy array is a central data structure of the numpy library. The library’s name is short for “Numeric Python” or “Numerical Python”.</p>

In [29]:
import numpy as np
np.__version__ # to check the version of numpy installed

'1.16.4'

<h3>arrays in numpy </h3>

In [52]:
##Normal 1D arrays, np.array
list1 = [1,2,3,4,5]
np.array(list1)
#or
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [61]:
#upcasting
np.array([1,2,3,4,5.0])

array([1., 2., 3., 4., 5.])

In [58]:
#dtypes in np.array
def dtype_array(dtype=None):
    print(np.array([1,2,3,4,5], dtype = dtype))
dtype_array()# default datatype to int
dtype_array(dtype=str)# dtype str
dtype_array(dtype=float)# dtype str
dtype_array(dtype=complex)#complex dtype

[1 2 3 4 5]
['1' '2' '3' '4' '5']
[1. 2. 3. 4. 5.]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


<p>arange - > Return an array object satisfying the specified requirements</p>
<p>ones -> Return a new array setting values to one</p>
<p>zeros - >Return a new array setting values to zero</p>
<p>empty -> Return a new uninitialized array</p>
<p>full -> Return a new array of given shape filled with value</p>
<p>ones_like -> Return an array of ones with shape and type of input</p>
<p>zeros_like -> Return an array of zeros with shape and type of input</p>
<p>empty_like -> Return an empty array with shape and type of input</p>
<p>full_like -> Return a new array with shape of input filled with value</p>

In [27]:
#np.linspace
#This function is similar to arange() function. In this function, instead of step size,
#the number of evenly spaced values between the interval is specified
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [38]:
##numpy arange
print("array of 3 elements -> ", np.arange(3))
print("array of 3 float elements ->", np.arange(3.0))
print("array of number between 3 and 7(exclude) ->", np.arange(3,7))
print("array of number between 3 and 7(exclude) seperated by 2 ->", np.arange(3,7,2))

array of 3 elements ->  [0 1 2]
array of 3 float elements -> [0. 1. 2.]
array of number between 3 and 7(exclude) -> [3 4 5 6]
array of number between 3 and 7(exclude) seperated by 2 -> [3 5]


In [63]:
#create your own 1D array
def make_array(start_value=0, end_value=10, seperate_by=2):# start and end values default to 0 and 10(excluded)
    print(np.arange(start_value, end_value, seperate_by))
    
make_array(4,80,5)
make_array(12,18,1.5)

[ 4  9 14 19 24 29 34 39 44 49 54 59 64 69 74 79]
[12.  13.5 15.  16.5]


In [99]:
#np.ones
print('1D array of ones\n', np.ones(5))
print('1D array of ones. dtype int\n',np.ones((5,), dtype=int))

print('nd array of ones\n', np.ones((5,4)))
print('nd array of ones. dtype int\n',np.ones((5,4), dtype=int))

1D array of ones
 [1. 1. 1. 1. 1.]
1D array of ones. dtype int
 [1 1 1 1 1]
nd array of ones
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
nd array of ones. dtype int
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [96]:
#np.zeros
print('1D array of zeros\n', np.zeros(6))
print('1D array of zeros. dtype int\n',np.zeros((6,), dtype=int))

print('nd array of zeros\n', np.zeros((2,3)))
print('nd array of zeros. dtype int \n',np.zeros((6,4), dtype=int))

1D array of zeros
 [0. 0. 0. 0. 0. 0.]
1D array of zeros. dtype int
 [0 0 0 0 0 0]
nd array of zeros
 [[0. 0. 0.]
 [0. 0. 0.]]
nd array of zeros. dtype int 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [98]:
#np.empty
#Return a new array of given shape and type, without initializing entries.
print('1d empty array\n', np.empty(2)) # one dimesional
print('nd empty array\n ',np.empty([2, 2], dtype=int)) # multi dimesional

1d empty array
 [1.5e-323 2.5e-323]
nd empty array
  [[10 10]
 [10 10]]


In [100]:
# np.full
#Return a new array of given shape and type, filled with fill_value.
print('one dimesional full array \n ', np.full(5,np.inf)) # array filled with np.inf
print('multi -dimensional full array \n', np.full((2, 2), 10)) #array filled with 10

one dimesional full array 
  [inf inf inf inf inf]
multi -dimensional full array 
 [[10 10]
 [10 10]]


<h3>nd arrays - 2d, 3d...</h3>

In [24]:
print(np.array([[1,2,3],[4,5,6]])) #normal 2d array
print(np.ones((2,3), dtype = int)) # ones array of shape (2,3)
print(np.zeros((2,3), dtype = int)) # eros array of shape (2,3)

[[1 2 3]
 [4 5 6]]
[[1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]]


In [16]:
#converting scaler 1d array into 2d array using reshape mathod
np.arange(2,10,2).reshape(2,2)

In [25]:
# to get shape and dtype of array
arr = np.arange(2,10,2).reshape(2,2)
print('arr shape ->', arr.shape)
print('arr dtype ->', arr.dtype)

arr shape -> (2, 2)
arr dtype -> int64


In [30]:
# Create an array with random values
np.random.random((2,2))

array([[0.95368014, 0.34622359],
       [0.42437044, 0.35883067]])

Some special arrays

In [36]:
#Return a 2-D array with ones on the diagonal and zeros elsewhere.
#k - int, optional
#Index of the diagonal: 0 (the default) refers to the main diagonal, 
#a positive value refers to an upper diagonal, and a negative value to a lower diagonal.
np.eye(5,dtype=int, k=1) 

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [37]:
#Return the identity array.
#The identity array is a square array with ones on the main diagonal.
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<h3> Array operations </h3>

with scalers

In [49]:
a = np.array(([1, 2, 3, 4],[4,5,6,7]))
print('addition->\n', a + 1) #addition of scaler value into array
print('multiplication->\n',a*2) #multiplication of scaler
print('subtraction->\n', a - 1) #subtraction of scaler value into array
print('division->\n',a/2) #division of scaler
print('combined->\n', (a+2)-1/3+4*2) #combined arithematic operations with scalers

addition->
 [[2 3 4 5]
 [5 6 7 8]]
multiplication->
 [[ 2  4  6  8]
 [ 8 10 12 14]]
subtraction->
 [[0 1 2 3]
 [3 4 5 6]]
division->
 [[0.5 1.  1.5 2. ]
 [2.  2.5 3.  3.5]]
combined->
 [[10.66666667 11.66666667 12.66666667 13.66666667]
 [13.66666667 14.66666667 15.66666667 16.66666667]]


In [55]:
#division by zero
a/0 # it gives warning but not error, we get inf in as array values

/home/suyash/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([[inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [56]:
#arithematic operation on ones array
b = np.ones(4) + 1
a-b

array([[-1.,  0.,  1.,  2.],
       [ 2.,  3.,  4.,  5.]])

In [59]:
#operation on arange
j = np.arange(5)
2**(j + 1) - j

array([ 2,  3,  6, 13, 28])

<p> Element-wise operations </p>

In [63]:
#element wise comparision
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
print('equals', a==b)
print('greater',a>b)

equals [False  True False  True]
greater [False False  True False]


In [65]:
# Array-wise comparisons:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([4, 2, 2, 4])
print(np.array_equal(a,b))
print(np.array_equal(c,b))

False
True


In [77]:
#Array multiplication is not matrix multiplication
o = np.ones((3, 3))
o*o   # NOT matrix multiplication! this is array multiplication

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [78]:
#this is matrix multiplication
o.dot(o)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [74]:
#Other operations
#Logical operations:
a = np.array([1, 0, 1, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)
print(np.logical_or(a, b)) #logical or
print(np.logical_and(a, b)) #logical and

[ True False  True False]
[ True False  True False]


In [73]:
#Transcendental functions:
a = np.arange(8)
print(np.sin(a))
print(np.log(a))
print(np.exp(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866 ]
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]


/home/suyash/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in log
  after removing the cwd from sys.path.


In [72]:
#Shape mismatches. errors
a = np.arange(5)
a + np.array([1, 2])  

ValueError: operands could not be broadcast together with shapes (5,) (2,) 

<h3> Indexing and slicing in numpy arrays </h3>
<p>Contents of ndarray object can be accessed
and modified by indexing or slicing, 
just like Python's in-built container objects.</p>

In [83]:
index_arr = np.array([1, 2, 3, 4])
#array index starts with 0
print(index_arr)
print(index_arr[0]) # 1 
print(index_arr[2]) # 3

[1 2 3 4]
1
3


Indexing in 2 dimensions

In [87]:
array_2d = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
# to fetch the item from 3rd row and 2nd column
print(array_2d[2, 1]) # 8

8


Picking a row or column of a 2d array

In [92]:
print('first row', array_2d[0]) # to fetch the first row
print('second column', array_2d[:,1]) # to fetch the second column

first row [1 2 3]
second column [2 5 8]


indexing in 3 dimesions

In [94]:
#3d arrays
array_3d = np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
               [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
               [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])

In [111]:
# fetch 3rd matrix , 1st row, 2nd element
print(array_3d[2, 0, 1]) # 31

31


In [112]:
# fetch first matrix, all rows, 1st column
print(array_3d[0, :, 1]) # [11 14 17]

[11 14 17]


Picking a matrix in a 3D array

In [115]:
#If we only specify the i index, numpy will return the corresponding matrix.
print('fetch 3rd metrix :\n',array_3d[2])
#step by step
print('use above matrix to open further: \n', array_3d[2][:,:2])

fetch 3rd metrix :
 [[30 31 32]
 [33 34 35]
 [36 37 38]]
use above matrix to open further: 
 [[30 31]
 [33 34]
 [36 37]]


In [114]:
#fetching 2nd row and 3rd column value from all matrice
print(array_3d[:, 1, 2]) # [15, 25, 35]

[15 25 35]
